### ISSUE TITLE
Question - Why not integrate into `mysql` module?

### ISSUE THREAD

**Issue by MarkHerhold** [daviemakz/mysql-connection-pool-manager#1]
Neat project! I'm wondering why this wouldn't be integrated into the Node.js `mysql` package directly. Any thoughts?

Also, have you considered making `mysql` a peer dependency so users can specify their own `mysql` version?

**Comment by daviemakz** [comment]
Thanks for the feedback!

I would be open to getting this functionality integrated into the `mysql` module, however it was a question of time for the most part. Such a change in the official `mysql` module would take quite some time to filter down to a release...

Hmm honestly I haven't considered that at all, what kind of issues could potentially arise from that?

**Comment by MarkHerhold** [comment]
Regarding the peer dependency, there could be a lot of issues if you use internal mysql module variables, but you can add ranges to what versions of mysql are allowed.

I think the Node.js docs state it well:

> One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient. You should not lock your peer dependencies down to specific patch versions. It would be really annoying if one Chai plugin peer-depended on Chai 1.4.1, while another depended on Chai 1.5.0, simply because the authors were lazy and didn't spend the time figuring out the actual minimum version of Chai they are compatible with.

https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies

**Comment by daviemakz** [comment]
Thanks Mark, 

Ill add this to the todo list & close when completed!

Cheers

**Comment by daviemakz** [comment]
Done, 8d9d66251f00a6118868d36db4d61c9844b5981c
