### ISSUE TITLE
Is to possible add streaming query?

### ISSUE THREAD

**Issue by expertup** [daviemakz/mysql-connection-pool-manager#23]
I think about similar code:

```
var query = connection.query('SELECT * FROM posts');
query
  .on('error', function(err) {
    // Handle error, an 'end' event will be emitted after this as well
  })
  .on('fields', function(fields) {
    // the field packets for the rows to follow
  })
  .on('result', function(row) {
    // Pausing the connnection is useful if your processing involves I/O
    connection.pause();

    processRow(row, function() {
      connection.resume();
    });
  })
  .on('end', function() {
    // all rows have been received
  });
```

This is streaming query. I'm using them i my project. 
Is any option to implement in this project?
Is any suggestions?

**Comment by daviemakz** [comment]
Hey,

It shouldn't be too much work to add in I think, i'll take a look at this for you.

Thanks,

David

**Comment by daviemakz** [comment]
Its possible to add however I have not found the time to do this yet. If you want to fork & submit a PR ill be happy to have a look and merge into the project
