### ISSUE TITLE
How to use Transaction without creating a raw connection first?

### ISSUE THREAD

**Issue by yangju** [daviemakz/mysql-connection-pool-manager#39]
Hi, I could not find example of using Transaction in this module. What I am doing is to create a raw connection first:
var connection  = pool.raw.createConnection({...});
then using the mysqljs/mysql's transaction:
connection.beginTransaction(function (err) {...}

Is there native support of transaction inside your module?
Also, I saw your in your example of using mysqljs/mysql's connection, you call
connection.end();
This will kill the connection. But what if I want to reuse the connection and want to release it back to the pool. Is there some api similar to the mysqljs/mysql's connection.release()?

Thanks.

**Comment by daviemakz** [comment]
Sorry not at the moment. You're more than welcome to add some support in for this!
