### ISSUE TITLE
Bulk insert like mysqljs

### ISSUE THREAD

**Issue by seventrust** [daviemakz/mysql-connection-pool-manager#8]
Hi! 

I have one problem using this lib, i have to do a bulk insert like in mysqljs module 

 this.connection.query(SQLstring, [values] , (error, result)=> {
  //..do error result check and return result 
})
where "[values]" is an array like -> 
values = [
    ['demian', 'demian@gmail.com', 1],
    ['john', 'john@gmail.com', 2],
    ['mark', 'mark@gmail.com', 3],
    ['pete', 'pete@gmail.com', 4]
];

Is there a way to do this with this lib? 
Just read tha documentation and doesn't explain this scenario.

Greetings...

**Comment by seventrust** [comment]
Hello

Well, due to the urgency of my project I had to add some validation in the pool.js file that verifies if there is an array for the bulk insert in the DB

I indicate below what I did and I hope you answer me if you want to add that to the project or I make a fork?

query(command, values, callback) {
    // Scope...
    values = values || undefined
.......

}

if(typeof scope.values !== undefined){
      scope.connection.query(scope.sqlCommand, scope.values, (err, rows) => {
....


} else {
      scope.connection.query(scope.sqlCommand, (err, rows) => {
....

**Comment by daviemakz** [comment]
Sorry for the late response, can you make a pull request with your changes?

**Comment by seventrust** [comment]
Ok, no problem, plz make sure to update on npm repository.

**Comment by daviemakz** [comment]
I will do once we get this merged, thanks for the effort!
